import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/navbar";
import Footer from './components/Footer';
import { montserrat, outfit } from "./fonts";

export const metadata: Metadata = {
  title: "Aashutosh Basnet",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} ${outfit.variable} antialiased`}
      >
        <Navbar />
        {children}
        <Footer />

      </body>
    </html>
  );
}
